# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/evgenijbojko/hse_project_game/GameProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/evgenijbojko/hse_project_game/GameProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/evgenijbojko/hse_project_game/GameProject/CMakeFiles /Users/evgenijbojko/hse_project_game/GameProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/evgenijbojko/hse_project_game/GameProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

Basic/Binder/Binder.o: Basic/Binder/Binder.cpp.o
.PHONY : Basic/Binder/Binder.o

# target to build an object file
Basic/Binder/Binder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Binder/Binder.cpp.o
.PHONY : Basic/Binder/Binder.cpp.o

Basic/Binder/Binder.i: Basic/Binder/Binder.cpp.i
.PHONY : Basic/Binder/Binder.i

# target to preprocess a source file
Basic/Binder/Binder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Binder/Binder.cpp.i
.PHONY : Basic/Binder/Binder.cpp.i

Basic/Binder/Binder.s: Basic/Binder/Binder.cpp.s
.PHONY : Basic/Binder/Binder.s

# target to generate assembly for a file
Basic/Binder/Binder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Binder/Binder.cpp.s
.PHONY : Basic/Binder/Binder.cpp.s

Basic/Game.o: Basic/Game.cpp.o
.PHONY : Basic/Game.o

# target to build an object file
Basic/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Game.cpp.o
.PHONY : Basic/Game.cpp.o

Basic/Game.i: Basic/Game.cpp.i
.PHONY : Basic/Game.i

# target to preprocess a source file
Basic/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Game.cpp.i
.PHONY : Basic/Game.cpp.i

Basic/Game.s: Basic/Game.cpp.s
.PHONY : Basic/Game.s

# target to generate assembly for a file
Basic/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Game.cpp.s
.PHONY : Basic/Game.cpp.s

Basic/KeyboardListener.o: Basic/KeyboardListener.cpp.o
.PHONY : Basic/KeyboardListener.o

# target to build an object file
Basic/KeyboardListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/KeyboardListener.cpp.o
.PHONY : Basic/KeyboardListener.cpp.o

Basic/KeyboardListener.i: Basic/KeyboardListener.cpp.i
.PHONY : Basic/KeyboardListener.i

# target to preprocess a source file
Basic/KeyboardListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/KeyboardListener.cpp.i
.PHONY : Basic/KeyboardListener.cpp.i

Basic/KeyboardListener.s: Basic/KeyboardListener.cpp.s
.PHONY : Basic/KeyboardListener.s

# target to generate assembly for a file
Basic/KeyboardListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/KeyboardListener.cpp.s
.PHONY : Basic/KeyboardListener.cpp.s

Basic/Message.o: Basic/Message.cpp.o
.PHONY : Basic/Message.o

# target to build an object file
Basic/Message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Message.cpp.o
.PHONY : Basic/Message.cpp.o

Basic/Message.i: Basic/Message.cpp.i
.PHONY : Basic/Message.i

# target to preprocess a source file
Basic/Message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Message.cpp.i
.PHONY : Basic/Message.cpp.i

Basic/Message.s: Basic/Message.cpp.s
.PHONY : Basic/Message.s

# target to generate assembly for a file
Basic/Message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Basic/Message.cpp.s
.PHONY : Basic/Message.cpp.s

Display/AbilityDrawer.o: Display/AbilityDrawer.cpp.o
.PHONY : Display/AbilityDrawer.o

# target to build an object file
Display/AbilityDrawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/AbilityDrawer.cpp.o
.PHONY : Display/AbilityDrawer.cpp.o

Display/AbilityDrawer.i: Display/AbilityDrawer.cpp.i
.PHONY : Display/AbilityDrawer.i

# target to preprocess a source file
Display/AbilityDrawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/AbilityDrawer.cpp.i
.PHONY : Display/AbilityDrawer.cpp.i

Display/AbilityDrawer.s: Display/AbilityDrawer.cpp.s
.PHONY : Display/AbilityDrawer.s

# target to generate assembly for a file
Display/AbilityDrawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/AbilityDrawer.cpp.s
.PHONY : Display/AbilityDrawer.cpp.s

Display/BattleViewManager.o: Display/BattleViewManager.cpp.o
.PHONY : Display/BattleViewManager.o

# target to build an object file
Display/BattleViewManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/BattleViewManager.cpp.o
.PHONY : Display/BattleViewManager.cpp.o

Display/BattleViewManager.i: Display/BattleViewManager.cpp.i
.PHONY : Display/BattleViewManager.i

# target to preprocess a source file
Display/BattleViewManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/BattleViewManager.cpp.i
.PHONY : Display/BattleViewManager.cpp.i

Display/BattleViewManager.s: Display/BattleViewManager.cpp.s
.PHONY : Display/BattleViewManager.s

# target to generate assembly for a file
Display/BattleViewManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/BattleViewManager.cpp.s
.PHONY : Display/BattleViewManager.cpp.s

Display/Display.o: Display/Display.cpp.o
.PHONY : Display/Display.o

# target to build an object file
Display/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/Display.cpp.o
.PHONY : Display/Display.cpp.o

Display/Display.i: Display/Display.cpp.i
.PHONY : Display/Display.i

# target to preprocess a source file
Display/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/Display.cpp.i
.PHONY : Display/Display.cpp.i

Display/Display.s: Display/Display.cpp.s
.PHONY : Display/Display.s

# target to generate assembly for a file
Display/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/Display.cpp.s
.PHONY : Display/Display.cpp.s

Display/Drawer.o: Display/Drawer.cpp.o
.PHONY : Display/Drawer.o

# target to build an object file
Display/Drawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/Drawer.cpp.o
.PHONY : Display/Drawer.cpp.o

Display/Drawer.i: Display/Drawer.cpp.i
.PHONY : Display/Drawer.i

# target to preprocess a source file
Display/Drawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/Drawer.cpp.i
.PHONY : Display/Drawer.cpp.i

Display/Drawer.s: Display/Drawer.cpp.s
.PHONY : Display/Drawer.s

# target to generate assembly for a file
Display/Drawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/Drawer.cpp.s
.PHONY : Display/Drawer.cpp.s

Display/HeroDrawer.o: Display/HeroDrawer.cpp.o
.PHONY : Display/HeroDrawer.o

# target to build an object file
Display/HeroDrawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/HeroDrawer.cpp.o
.PHONY : Display/HeroDrawer.cpp.o

Display/HeroDrawer.i: Display/HeroDrawer.cpp.i
.PHONY : Display/HeroDrawer.i

# target to preprocess a source file
Display/HeroDrawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/HeroDrawer.cpp.i
.PHONY : Display/HeroDrawer.cpp.i

Display/HeroDrawer.s: Display/HeroDrawer.cpp.s
.PHONY : Display/HeroDrawer.s

# target to generate assembly for a file
Display/HeroDrawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/HeroDrawer.cpp.s
.PHONY : Display/HeroDrawer.cpp.s

Display/InventoryViewManager.o: Display/InventoryViewManager.cpp.o
.PHONY : Display/InventoryViewManager.o

# target to build an object file
Display/InventoryViewManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/InventoryViewManager.cpp.o
.PHONY : Display/InventoryViewManager.cpp.o

Display/InventoryViewManager.i: Display/InventoryViewManager.cpp.i
.PHONY : Display/InventoryViewManager.i

# target to preprocess a source file
Display/InventoryViewManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/InventoryViewManager.cpp.i
.PHONY : Display/InventoryViewManager.cpp.i

Display/InventoryViewManager.s: Display/InventoryViewManager.cpp.s
.PHONY : Display/InventoryViewManager.s

# target to generate assembly for a file
Display/InventoryViewManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/InventoryViewManager.cpp.s
.PHONY : Display/InventoryViewManager.cpp.s

Display/ItemDrawer.o: Display/ItemDrawer.cpp.o
.PHONY : Display/ItemDrawer.o

# target to build an object file
Display/ItemDrawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/ItemDrawer.cpp.o
.PHONY : Display/ItemDrawer.cpp.o

Display/ItemDrawer.i: Display/ItemDrawer.cpp.i
.PHONY : Display/ItemDrawer.i

# target to preprocess a source file
Display/ItemDrawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/ItemDrawer.cpp.i
.PHONY : Display/ItemDrawer.cpp.i

Display/ItemDrawer.s: Display/ItemDrawer.cpp.s
.PHONY : Display/ItemDrawer.s

# target to generate assembly for a file
Display/ItemDrawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Display/ItemDrawer.cpp.s
.PHONY : Display/ItemDrawer.cpp.s

Events/AbilityManager.o: Events/AbilityManager.cpp.o
.PHONY : Events/AbilityManager.o

# target to build an object file
Events/AbilityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/AbilityManager.cpp.o
.PHONY : Events/AbilityManager.cpp.o

Events/AbilityManager.i: Events/AbilityManager.cpp.i
.PHONY : Events/AbilityManager.i

# target to preprocess a source file
Events/AbilityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/AbilityManager.cpp.i
.PHONY : Events/AbilityManager.cpp.i

Events/AbilityManager.s: Events/AbilityManager.cpp.s
.PHONY : Events/AbilityManager.s

# target to generate assembly for a file
Events/AbilityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/AbilityManager.cpp.s
.PHONY : Events/AbilityManager.cpp.s

Events/BattleEventListener.o: Events/BattleEventListener.cpp.o
.PHONY : Events/BattleEventListener.o

# target to build an object file
Events/BattleEventListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/BattleEventListener.cpp.o
.PHONY : Events/BattleEventListener.cpp.o

Events/BattleEventListener.i: Events/BattleEventListener.cpp.i
.PHONY : Events/BattleEventListener.i

# target to preprocess a source file
Events/BattleEventListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/BattleEventListener.cpp.i
.PHONY : Events/BattleEventListener.cpp.i

Events/BattleEventListener.s: Events/BattleEventListener.cpp.s
.PHONY : Events/BattleEventListener.s

# target to generate assembly for a file
Events/BattleEventListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/BattleEventListener.cpp.s
.PHONY : Events/BattleEventListener.cpp.s

Events/BattleInventoryEventListener.o: Events/BattleInventoryEventListener.cpp.o
.PHONY : Events/BattleInventoryEventListener.o

# target to build an object file
Events/BattleInventoryEventListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/BattleInventoryEventListener.cpp.o
.PHONY : Events/BattleInventoryEventListener.cpp.o

Events/BattleInventoryEventListener.i: Events/BattleInventoryEventListener.cpp.i
.PHONY : Events/BattleInventoryEventListener.i

# target to preprocess a source file
Events/BattleInventoryEventListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/BattleInventoryEventListener.cpp.i
.PHONY : Events/BattleInventoryEventListener.cpp.i

Events/BattleInventoryEventListener.s: Events/BattleInventoryEventListener.cpp.s
.PHONY : Events/BattleInventoryEventListener.s

# target to generate assembly for a file
Events/BattleInventoryEventListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/BattleInventoryEventListener.cpp.s
.PHONY : Events/BattleInventoryEventListener.cpp.s

Events/FieldEventListener.o: Events/FieldEventListener.cpp.o
.PHONY : Events/FieldEventListener.o

# target to build an object file
Events/FieldEventListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/FieldEventListener.cpp.o
.PHONY : Events/FieldEventListener.cpp.o

Events/FieldEventListener.i: Events/FieldEventListener.cpp.i
.PHONY : Events/FieldEventListener.i

# target to preprocess a source file
Events/FieldEventListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/FieldEventListener.cpp.i
.PHONY : Events/FieldEventListener.cpp.i

Events/FieldEventListener.s: Events/FieldEventListener.cpp.s
.PHONY : Events/FieldEventListener.s

# target to generate assembly for a file
Events/FieldEventListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/FieldEventListener.cpp.s
.PHONY : Events/FieldEventListener.cpp.s

Events/HeroManager.o: Events/HeroManager.cpp.o
.PHONY : Events/HeroManager.o

# target to build an object file
Events/HeroManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/HeroManager.cpp.o
.PHONY : Events/HeroManager.cpp.o

Events/HeroManager.i: Events/HeroManager.cpp.i
.PHONY : Events/HeroManager.i

# target to preprocess a source file
Events/HeroManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/HeroManager.cpp.i
.PHONY : Events/HeroManager.cpp.i

Events/HeroManager.s: Events/HeroManager.cpp.s
.PHONY : Events/HeroManager.s

# target to generate assembly for a file
Events/HeroManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/HeroManager.cpp.s
.PHONY : Events/HeroManager.cpp.s

Events/IneventoryEventListener.o: Events/IneventoryEventListener.cpp.o
.PHONY : Events/IneventoryEventListener.o

# target to build an object file
Events/IneventoryEventListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/IneventoryEventListener.cpp.o
.PHONY : Events/IneventoryEventListener.cpp.o

Events/IneventoryEventListener.i: Events/IneventoryEventListener.cpp.i
.PHONY : Events/IneventoryEventListener.i

# target to preprocess a source file
Events/IneventoryEventListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/IneventoryEventListener.cpp.i
.PHONY : Events/IneventoryEventListener.cpp.i

Events/IneventoryEventListener.s: Events/IneventoryEventListener.cpp.s
.PHONY : Events/IneventoryEventListener.s

# target to generate assembly for a file
Events/IneventoryEventListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/IneventoryEventListener.cpp.s
.PHONY : Events/IneventoryEventListener.cpp.s

Events/MainMenuEventListener.o: Events/MainMenuEventListener.cpp.o
.PHONY : Events/MainMenuEventListener.o

# target to build an object file
Events/MainMenuEventListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/MainMenuEventListener.cpp.o
.PHONY : Events/MainMenuEventListener.cpp.o

Events/MainMenuEventListener.i: Events/MainMenuEventListener.cpp.i
.PHONY : Events/MainMenuEventListener.i

# target to preprocess a source file
Events/MainMenuEventListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/MainMenuEventListener.cpp.i
.PHONY : Events/MainMenuEventListener.cpp.i

Events/MainMenuEventListener.s: Events/MainMenuEventListener.cpp.s
.PHONY : Events/MainMenuEventListener.s

# target to generate assembly for a file
Events/MainMenuEventListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Events/MainMenuEventListener.cpp.s
.PHONY : Events/MainMenuEventListener.cpp.s

GameData/Ability.o: GameData/Ability.cpp.o
.PHONY : GameData/Ability.o

# target to build an object file
GameData/Ability.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Ability.cpp.o
.PHONY : GameData/Ability.cpp.o

GameData/Ability.i: GameData/Ability.cpp.i
.PHONY : GameData/Ability.i

# target to preprocess a source file
GameData/Ability.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Ability.cpp.i
.PHONY : GameData/Ability.cpp.i

GameData/Ability.s: GameData/Ability.cpp.s
.PHONY : GameData/Ability.s

# target to generate assembly for a file
GameData/Ability.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Ability.cpp.s
.PHONY : GameData/Ability.cpp.s

GameData/Cell.o: GameData/Cell.cpp.o
.PHONY : GameData/Cell.o

# target to build an object file
GameData/Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Cell.cpp.o
.PHONY : GameData/Cell.cpp.o

GameData/Cell.i: GameData/Cell.cpp.i
.PHONY : GameData/Cell.i

# target to preprocess a source file
GameData/Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Cell.cpp.i
.PHONY : GameData/Cell.cpp.i

GameData/Cell.s: GameData/Cell.cpp.s
.PHONY : GameData/Cell.s

# target to generate assembly for a file
GameData/Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Cell.cpp.s
.PHONY : GameData/Cell.cpp.s

GameData/Field.o: GameData/Field.cpp.o
.PHONY : GameData/Field.o

# target to build an object file
GameData/Field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Field.cpp.o
.PHONY : GameData/Field.cpp.o

GameData/Field.i: GameData/Field.cpp.i
.PHONY : GameData/Field.i

# target to preprocess a source file
GameData/Field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Field.cpp.i
.PHONY : GameData/Field.cpp.i

GameData/Field.s: GameData/Field.cpp.s
.PHONY : GameData/Field.s

# target to generate assembly for a file
GameData/Field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Field.cpp.s
.PHONY : GameData/Field.cpp.s

GameData/GameData.o: GameData/GameData.cpp.o
.PHONY : GameData/GameData.o

# target to build an object file
GameData/GameData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/GameData.cpp.o
.PHONY : GameData/GameData.cpp.o

GameData/GameData.i: GameData/GameData.cpp.i
.PHONY : GameData/GameData.i

# target to preprocess a source file
GameData/GameData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/GameData.cpp.i
.PHONY : GameData/GameData.cpp.i

GameData/GameData.s: GameData/GameData.cpp.s
.PHONY : GameData/GameData.s

# target to generate assembly for a file
GameData/GameData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/GameData.cpp.s
.PHONY : GameData/GameData.cpp.s

GameData/Hero.o: GameData/Hero.cpp.o
.PHONY : GameData/Hero.o

# target to build an object file
GameData/Hero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Hero.cpp.o
.PHONY : GameData/Hero.cpp.o

GameData/Hero.i: GameData/Hero.cpp.i
.PHONY : GameData/Hero.i

# target to preprocess a source file
GameData/Hero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Hero.cpp.i
.PHONY : GameData/Hero.cpp.i

GameData/Hero.s: GameData/Hero.cpp.s
.PHONY : GameData/Hero.s

# target to generate assembly for a file
GameData/Hero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Hero.cpp.s
.PHONY : GameData/Hero.cpp.s

GameData/Inventory.o: GameData/Inventory.cpp.o
.PHONY : GameData/Inventory.o

# target to build an object file
GameData/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Inventory.cpp.o
.PHONY : GameData/Inventory.cpp.o

GameData/Inventory.i: GameData/Inventory.cpp.i
.PHONY : GameData/Inventory.i

# target to preprocess a source file
GameData/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Inventory.cpp.i
.PHONY : GameData/Inventory.cpp.i

GameData/Inventory.s: GameData/Inventory.cpp.s
.PHONY : GameData/Inventory.s

# target to generate assembly for a file
GameData/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Inventory.cpp.s
.PHONY : GameData/Inventory.cpp.s

GameData/Item.o: GameData/Item.cpp.o
.PHONY : GameData/Item.o

# target to build an object file
GameData/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Item.cpp.o
.PHONY : GameData/Item.cpp.o

GameData/Item.i: GameData/Item.cpp.i
.PHONY : GameData/Item.i

# target to preprocess a source file
GameData/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Item.cpp.i
.PHONY : GameData/Item.cpp.i

GameData/Item.s: GameData/Item.cpp.s
.PHONY : GameData/Item.s

# target to generate assembly for a file
GameData/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameData/Item.cpp.s
.PHONY : GameData/Item.cpp.s

Manager.o: Manager.cpp.o
.PHONY : Manager.o

# target to build an object file
Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Manager.cpp.o
.PHONY : Manager.cpp.o

Manager.i: Manager.cpp.i
.PHONY : Manager.i

# target to preprocess a source file
Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Manager.cpp.i
.PHONY : Manager.cpp.i

Manager.s: Manager.cpp.s
.PHONY : Manager.s

# target to generate assembly for a file
Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Manager.cpp.s
.PHONY : Manager.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... Basic/Binder/Binder.o"
	@echo "... Basic/Binder/Binder.i"
	@echo "... Basic/Binder/Binder.s"
	@echo "... Basic/Game.o"
	@echo "... Basic/Game.i"
	@echo "... Basic/Game.s"
	@echo "... Basic/KeyboardListener.o"
	@echo "... Basic/KeyboardListener.i"
	@echo "... Basic/KeyboardListener.s"
	@echo "... Basic/Message.o"
	@echo "... Basic/Message.i"
	@echo "... Basic/Message.s"
	@echo "... Display/AbilityDrawer.o"
	@echo "... Display/AbilityDrawer.i"
	@echo "... Display/AbilityDrawer.s"
	@echo "... Display/BattleViewManager.o"
	@echo "... Display/BattleViewManager.i"
	@echo "... Display/BattleViewManager.s"
	@echo "... Display/Display.o"
	@echo "... Display/Display.i"
	@echo "... Display/Display.s"
	@echo "... Display/Drawer.o"
	@echo "... Display/Drawer.i"
	@echo "... Display/Drawer.s"
	@echo "... Display/HeroDrawer.o"
	@echo "... Display/HeroDrawer.i"
	@echo "... Display/HeroDrawer.s"
	@echo "... Display/InventoryViewManager.o"
	@echo "... Display/InventoryViewManager.i"
	@echo "... Display/InventoryViewManager.s"
	@echo "... Display/ItemDrawer.o"
	@echo "... Display/ItemDrawer.i"
	@echo "... Display/ItemDrawer.s"
	@echo "... Events/AbilityManager.o"
	@echo "... Events/AbilityManager.i"
	@echo "... Events/AbilityManager.s"
	@echo "... Events/BattleEventListener.o"
	@echo "... Events/BattleEventListener.i"
	@echo "... Events/BattleEventListener.s"
	@echo "... Events/BattleInventoryEventListener.o"
	@echo "... Events/BattleInventoryEventListener.i"
	@echo "... Events/BattleInventoryEventListener.s"
	@echo "... Events/FieldEventListener.o"
	@echo "... Events/FieldEventListener.i"
	@echo "... Events/FieldEventListener.s"
	@echo "... Events/HeroManager.o"
	@echo "... Events/HeroManager.i"
	@echo "... Events/HeroManager.s"
	@echo "... Events/IneventoryEventListener.o"
	@echo "... Events/IneventoryEventListener.i"
	@echo "... Events/IneventoryEventListener.s"
	@echo "... Events/MainMenuEventListener.o"
	@echo "... Events/MainMenuEventListener.i"
	@echo "... Events/MainMenuEventListener.s"
	@echo "... GameData/Ability.o"
	@echo "... GameData/Ability.i"
	@echo "... GameData/Ability.s"
	@echo "... GameData/Cell.o"
	@echo "... GameData/Cell.i"
	@echo "... GameData/Cell.s"
	@echo "... GameData/Field.o"
	@echo "... GameData/Field.i"
	@echo "... GameData/Field.s"
	@echo "... GameData/GameData.o"
	@echo "... GameData/GameData.i"
	@echo "... GameData/GameData.s"
	@echo "... GameData/Hero.o"
	@echo "... GameData/Hero.i"
	@echo "... GameData/Hero.s"
	@echo "... GameData/Inventory.o"
	@echo "... GameData/Inventory.i"
	@echo "... GameData/Inventory.s"
	@echo "... GameData/Item.o"
	@echo "... GameData/Item.i"
	@echo "... GameData/Item.s"
	@echo "... Manager.o"
	@echo "... Manager.i"
	@echo "... Manager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

